---

- name: Create certs directory
  file:
    path: /etc/octavia/certs/
    state: directory

- name: Copy certificates
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ octavia_system_user_name }}"
    group: "{{ octavia_system_group_name }}"
    mode: "0640"
  with_items:
    - content: "{{ hostvars[octavia_cert_setup_host]['octavia_ca_private_key_fact'] }}"
      dest: "/etc/octavia/certs/ca_key.pem"
    - content: "{{ hostvars[octavia_cert_setup_host]['octavia_ca_certificate_fact'] }}"
      dest: "/etc/octavia/certs/ca.pem"
    - content: "{{ hostvars[octavia_cert_setup_host]['octavia_server_ca_fact'] }}"
      dest: "/etc/octavia/certs/server_ca.pem"
    - content: "{{ hostvars[octavia_cert_setup_host]['octavia_client_ca_fact'] }}"
      dest: "/etc/octavia/certs/client_ca.pem"
    - content: "{{ hostvars[octavia_cert_setup_host]['octavia_client_cert_fact'] }}"
      dest: "/etc/octavia/certs/client.pem"
  notify:
    - Restart octavia services
    - Restart uwsgi services
